### DISCUSSION TITLE
VCPKG_MANIFEST_FEATURES should skip empty list elements

### DISCUSSION THREAD

**Discussion by friendlyanon** [microsoft/vcpkg#19192] [Ideas]
****

**Is your feature request related to a problem? Please describe.**
`VCPKG_MANIFEST_FEATURES` skipping empty list elements would improve usability in CI matrices where a feature comes from the `matrix` context and could be empty.

**Proposed solution**
The loop in `vcpkg.cmake` iterating over `VCPKG_MANIFEST_FEATURES` could only conditionally append the `--x-feature` arguments using an `if(NOT Z_VCPKG_FEATURE STREQUAL "")` conditional.

**Describe alternatives you've considered**
None.

**Additional context**
It would be ideal to be able to have a CI workflow written like so:
```yml
strategy:
  matrix:
    feature: [foo, ""]
...
    - run: cmake -D "VCPKG_MANIFEST_FEATURES=test;${{ matrix.feature }}" ...
```
One option here would be to move the semicolon into the matrix, but that's not as aesthetic and for some it might not even be obvious why the semicolon must be where it is.

Since it is not possible to pass an empty `--x-feature=` argument to the vcpkg tool, this would not break anything.
