### DISCUSSION TITLE
How do I control repository association of vcpkg NuGet packages from GitHub actions?

### DISCUSSION THREAD

**Discussion by equeim** [microsoft/vcpkg#23285] [Q&A]
I use vcpkg with NuGet binary caching via GitHub Packages in my GitHub actions workflow.
It works fine with single repository but fails with multiple repos due to repository association of uploaded NuGet packages.

I.e. repository Foo runs Actions workflow in which vcpkg builds some packages and automatically uploads them to GitHub Packages using NuGet. Now these packages are associated with repository Foo.
Now if repository Bar has the same vcpkg dependencies with same versions, then when its workflow is run vcpkg can successfully download them from GitHub Packages.
If I then update versions of these dependencies in repository Bar, then vcpkg will rebuild them and fail to upload new versions to GitHub Packages because they are already associated with repository Foo.

How can I circumvent this issue?

**Comment by JamieStM** [comment]
I know I'm far too late for OP, but for future users that come across this issue:

Set the undocumented `X_VCPKG_NUGET_ID_PREFIX` environment variable to a unique name per-repo, e.g. (where `<OWNER>` is either your account name or your organization's name, as in the [tutorial](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-packages?pivots=linux-runner#4---add-github-packages-as-a-nuget-source))

```
    - shell: bash
      env:
        VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/<OWNER>/index.json,readwrite"
        X_VCPKG_NUGET_ID_PREFIX: "${GITHUB_REPOSITORY}"
      run: <cmake configure or vcpkg install command>
```

This won't control repository association of the vcpkg nuget packages, but it will allow you to essentially create a separate nuget feed for each repository so that they no longer interfere with each other.

See discussions and PRs introducing the feature here:

https://github.com/microsoft/vcpkg/issues/16579
https://github.com/microsoft/vcpkg/discussions/19103
https://github.com/microsoft/vcpkg/issues/19095
https://github.com/microsoft/vcpkg-tool/pull/40
https://github.com/microsoft/vcpkg-tool/pull/192
