### DISCUSSION TITLE
Add a vcpkg argument that will print the hash that will be used as a base for caching binaries

### DISCUSSION THREAD

**Discussion by thomasnal** [microsoft/vcpkg#27886] [Ideas]
****

**Is your feature request related to a problem? Please describe.**
vcpkg to be usable in CI/CD pipelines like Github Actions, we need to be able to effectively store the cached binaries placed to archives folder.  To restore content of the archives folder before running `vcpkg install` we need to know what is the hash that vcpkg is going to use so that we can ask CI/CD to restore content of the archives folder that vcpkg is going to use.

Many times vcpkg ignores the archives, does not restore the binaries, builds new ones and copies the binaries over to the archives folder that contains the previous built, effectively spoiling a chance to store/restore the new built.  vcpkg ignores the archives because during the run it detects that some of the many data it uses to calculate the hash has changed.

We need to be able to ask vcpkg for a single hash that will be used by vcpkg to determine if the archive cache binaries will be used.  We can use this hash key to ask CI/CD provider's cache to restore the correct binaries. 

**Proposed solution**
Add a parameter that prints a hash, based on triplet hash and other information, that is used to determine if vcpkg is going to use the cached binaries in the archives folder.

**Describe alternatives you've considered**
First, we determined the cache key used with the CI/CD by calculating hash sum of the vcpkg.json.  That is not enough since vcpkg takes into account many other information that is not clear or difficult to calculate the same way as vcpkg does.

Also tried `VCPKG_DISABLE_COMPILER_TRACKING=1`.

**Comment by thomasnal** [comment]
A Github Actions attempt to store/restore the archives that does not work with vcpkg.
```
      - uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

      - name: Configure
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg/scripts/buildsystems/vcpkg.cmake ` .
```
Instead of `hashFiles('vcpkg.json')` I would like to do `vcpkg --binary-cache-hash`.
