### DISCUSSION TITLE
How to fetch overlay ports from AzureDevops Pipeline

### DISCUSSION THREAD

**Discussion by Galatis-Giuliano** [microsoft/vcpkg#41401] [Q&A] [answered]
Hello,

I'm trying to access some overlay ports I created from AzureDevops in a pipeline. I am having trouble and seeing this kind of error:

`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):`
```
1> Call Stack (most recent call first):
1>  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
1>  D:/a/1/s/Project/ports/dependencyName/portfile.cmake:11 (vcpkg_from_git)
1>  scripts/ports.cmake:192 (include)
```
issue_body:

Package: repo:x64-windows@1.0.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.41.34120.0
-    vcpkg-tool version: 2024-09-18-5f5da308dd1dd3cc49641c60eafff176e248a9dd
    vcpkg-scripts version: 76d153790 2024-09-27 (10 days ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Fetching git@ssh.dev.azure.com:v3/Organization/Project/repo 8d8dc0cf6210d1537896a6b64840390d788ad54f...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/agents/3.245.0/externals/git/cmd/git.exe fetch git@ssh.dev.azure.com:v3/Organization/Project/repo 8d8dc0cf6210d1537896a6b64840390d788ad54f --depth 1 -n
    Working Directory: C:/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      C:\vcpkg\buildtrees\repo\git-fetch-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  D:/a/1/s/BackendProject/ports/repo/portfile.cmake:11 (vcpkg_from_git)
  scripts/ports.cmake:192 (include)



```

<details><summary>C:\vcpkg\buildtrees\repo\git-fetch-x64-windows-err.log</summary>

```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "dependencies": [
    "vcpkg-msbuild",
    "boost-any",
    "boost-asio",
    "boost-iostreams",
    "boost-multiprecision",
    "boost-thread",
    "boost-uuid",
    "eigen3",
    "librdkafka",
    "openssl",
    "pcre2",
    "poco",
    "protobuf",
    "pugixml",
    "boost-chrono",
    "boost-numeric-conversion",
    "grpc",
    "repo"
  ]
}

```
</details>

I suspect this is because I am not setting up my ssh key correctly on the runner. Is there a good guide or template for this? I tried following the guide here:
[Azure DevOps pipeline: Access multiple repositories with SSH Keys](https://medium.com/@mr.mornesnyman/azure-devops-pipeline-access-multiple-repositories-with-ssh-keys-43acfd1d9484)

I'm trying to replicate the steps I was able to do locally from this guide:
[Tutorial: Package a private Azure DevOps dependency](https://learn.microsoft.com/en-us/vcpkg/produce/package-ado-dependency)

Here is what I've been trying:

```
variables:
  - group: ssh-key

jobs:
  - job: Build
    timeoutInMinutes: 0
    steps:

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(known_host)'
    sshKeySecureFile: 'id_rsa'

- task: CmdLine@2
  inputs:
    script: 'vcpkg integrate install'

- task: CmdLine@2
  inputs:
    script: 'vcpkg install --debug'
    workingDirectory: '$(System.DefaultWorkingDirectory)\SubDirectory' #contains vcpkg.json
```

I managed to get the git-fetch-x64-windows-err.log
[git-fetch-x64-windows-err.log](https://github.com/user-attachments/files/17284532/git-fetch-x64-windows-err.log)

The runner uses windows-2022. Any help is appreciated.

Thank You
