### ISSUE TITLE
vcpkg.cmake error:  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

### ISSUE THREAD

**Issue by justin-hackin** [microsoft/vcpkg#14815]
**Describe the bug**
Usage of vcpkg.cmake in cmake arg -DCMAKE_TOOLCHAIN_FILE results in an error regarding missing PkgConfigure.

**Environment**
- OS: Appveyor image: Visual Studio 2017 (Windows 10)
- Compiler: vcpkg 2019.09.12-nohash

**To Reproduce**

Appveyor config (environment details here https://www.appveyor.com/docs/windows-images-software):
```
image: Visual Studio 2017
environment:
  nodejs_version: "14"
  Path: $(yarn global bin);$(Path)
  VCPKG_DEFAULT_TRIPLET: x64-windows

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - c:\tools\vcpkg\installed\
  - $(yarn global bin)
  - $(yarn global dir)

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - vcpkg install gsl:x64-windows
  - vcpkg install gsl:x64-windows
  - vcpkg install double-conversion:x64-windows
  - vcpkg install cairo:x64-windows
  - yarn global add cmake-js
  # https://www.appveyor.com/docs/windows-images-software/#boost
  - npm config set cmake_BOOST_ROOT "C:\Libraries\boost_1_69_0"
  - npm config set cmake_CMAKE_TOOLCHAIN_FILE "c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - yarn

build_script:
  - yarn release --win

test: false
```

with npm project containing https://github.com/justin-hackin/lib2geom-path-boolean-addon as a dependency.

**Expected behavior**
The node.js addon is successfully built (succeeds on Ubuntu 20.04).

**Failure logs** 

```
Command: cmake-js compile
Arguments: 
Directory: C:\projects\polyhedral-net-factory\node_modules\lib2geom-path-boolean
Output:
[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\appveyor\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\cmake-js\\bin\\cmake-js',
  'compile'
]
info TOOL Using Visual Studio 15 2017 Win64 generator.
info DIST Downloading distribution files.
http DIST 	- https://atom.io/download/atom-shell/v6.1.0/x64/node.lib
http DIST 	- https://atom.io/download/atom-shell/v6.1.0/node-v6.1.0.tar.gz
info CMD CONFIGURE
info RUN cmake "C:\projects\polyhedral-net-factory\node_modules\lib2geom-path-boolean" --no-warn-unused-cli -G"Visual Studio 15 2017 Win64" -DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="C:\projects\polyhedral-net-factory\node_modules\lib2geom-path-boolean\build" -DCMAKE_JS_INC="C:\Users\appveyor\.cmake-js\electron-x64\v6.1.0\include\node;C:\projects\polyhedral-net-factory\node_modules\nan" -DCMAKE_JS_SRC="C:/Users/appveyor/AppData/Local/Yarn/Data/global/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" -DNODE_RUNTIME="electron" -DNODE_RUNTIMEVERSION="6.1.0" -DNODE_ARCH="x64" -DCMAKE_JS_LIB="C:\Users\appveyor\.cmake-js\electron-x64\v6.1.0\x64\node.lib" -DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE" -DBOOST_ROOT="C:\Libraries\boost_1_69_0" -DCMAKE_TOOLCHAIN_FILE="c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
Not searching for unused variables given on the command line.
-- The C compiler identification is MSVC 19.16.27035.0
-- The CXX compiler identification is MSVC 19.16.27035.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: C:/Libraries/boost_1_69_0 (found suitable version "1.69.0", minimum required is "1.40")  
-- Found DoubleConversion: C:/Tools/vcpkg/installed/x64-windows/lib/double-conversion.lib  
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
  lib2geom/CMakeLists.txt:35 (find_package)
```
