### ISSUE TITLE
External code being injected into binary

### ISSUE THREAD

**Issue by dgengin** [microsoft/vcpkg#15525]
**Describe the bug**
The binaries built using GitHub Actions are around 600KB bigger than my local buids. Upon inspection of the binaries, I saw a bunch of javascript code injected into it.

The artifacts are built using a Windows-2019 image and use vcpkg to fetch sfml and physfs. Although I override the port with a custom one in some actions, I don't do this in all and all of the artifacts that are using these 2 ports have this problem, including the ones that use a vanilla vcpkg port.

Since these ports include a few others (vorbis, zlib, flac, etc), I'm guessing one of those is including the extra code.

example: https://github.com/dgengin/Columns

to see the injected code, open the binary with a text processor and search for "san francisco".

**Environment**
- OS: Windows
- Compiler: vs2019-latest stable

Locally, I'm using an older version of vcpkg: 2020.02.04-nohash
windows-2019 version: Vcpkg 2020.11.12 (build from master ) - https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

**To Reproduce**

from the github actions yaml file:
```yaml
    - name: Install dependencies
      if: steps.cache-windows.outputs.cache-hit != 'true'
      run: vcpkg install physfs:x86-windows-static sfml:x86-windows-static

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: MSBuild Columns
      run: |
        vcpkg integrate install
        msbuild Project.vcxproj /p:Configuration="Release Static NoMovie" /p:Platform=Win32
```
https://github.com/dgengin/Columns

**Expected behavior**
The binary file shouldn't have the extra code in it.

**Failure logs** 
I've attached the Columns artifact produced by github actions with the problem.
[Columns-windows-x86.zip](https://github.com/microsoft/vcpkg/files/5787310/Columns-windows-x86.zip)

**Additional context**
