### ISSUE TITLE
[manifest] Add diagnostic information to prompt the user

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#21631]
All I could find is https://github.com/microsoft/vcpkg-tool/commit/93c2aa37f4f3ab0abac3bde6ef6ceb00075023fa

My commit last night worked:
https://github.com/offscale/libacquire/actions/runs/1493273483/workflow

My commit today doesn't:
https://github.com/offscale/libacquire/actions/runs/1496412619/workflow

Failing output:
```
  shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
Vcpkg package management program version 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

See LICENSE.txt for license information.
Error: 'install' requires 0 arguments, but 1 were provided.
Example:
  vcpkg install --triplet x64-windows

Options:
  --dry-run                       Do not actually build or install
  --head                          Install the libraries on the command line using the latest
                                  upstream sources
  --no-downloads                  Do not download new sources
  --only-downloads                Download sources but don't build packages
  --only-binarycaching            Fail if cached binaries are not available
  --recurse                       Allow removal of packages as part of installation
  --keep-going                    Continue installing packages on failure
  --editable                      Disable source re-extraction and binary caching for libraries on
                                  the command line
  --x-use-aria2                   Use aria2 to perform download tasks
  --clean-after-build             Clean buildtrees, packages and downloads after building each
                                  package
  --clean-buildtrees-after-build  Clean buildtrees after building each package
  --clean-packages-after-build    Clean packages after building each package
  --clean-downloads-after-build   Clean downloads after building each package
  --x-no-default-features         Don't install the default features from the manifest.
  --enforce-port-checks           Fail install if a port has detected problems or attempts to use a
                                  deprecated feature
  --allow-unsupported             Instead of erroring on an unsupported port, continue with a
                                  warning.
  --x-xunit=...                   File to output results in XUnit format (Internal use)
  --x-write-nuget-packages-config=...
                                  Writes out a NuGet packages.config-formatted file for use with
                                  external binary caching.
                                  See `vcpkg help binarycaching` for more information.
  --x-feature=...                 A feature from the manifest to install.
  --triplet=<t>                   Specify the target architecture triplet. See 'vcpkg help triplet'
                                  (default: %VCPKG_DEFAULT_TRIPLET%)
  --host-triplet=<t>              Specify the host architecture triplet. See 'vcpkg help triplet'
                                  (default: %VCPKG_DEFAULT_HOST_TRIPLET%)
  --overlay-ports=<path>          Specify directories to be used when searching for ports
                                  (also: %VCPKG_OVERLAY_PORTS%)
  --overlay-triplets=<path>       Specify directories containing triplets files
                                  (also: %VCPKG_OVERLAY_TRIPLETS%)
  --binarysource=<path>           Add sources for binary caching. See 'vcpkg help binarycaching'
  --x-asset-sources=<path>        Add sources for asset caching. See 'vcpkg help assetcaching'
  --downloads-root=<path>         Specify the downloads root directory
                                  (default: %VCPKG_DOWNLOADS%)
  --vcpkg-root=<path>             Specify the vcpkg root directory
                                  (default: %VCPKG_ROOT%)
  --x-buildtrees-root=<path>      (Experimental) Specify the buildtrees root directory
  --x-install-root=<path>         (Experimental) Specify the install root directory
  --x-packages-root=<path>        (Experimental) Specify the packages root directory
  --x-scripts-root=<path>         (Experimental) Specify the scripts root directory
  --x-builtin-ports-root=<path>   (Experimental) Specify the packages root directory
  --x-builtin-registry-versions-dir=<path>
                                  (Experimental) Specify the versions root directory
  --x-json                        (Experimental) Request JSON output
```

**Comment by SamuelMarks** [comment]
Looks like `--triplet` is now required, it's progressing: https://github.com/offscale/libacquire/actions/runs/1496488166/workflow#L81

Not sure if this issue should be closed or kept open so others can add their perspective

**Comment by autoantwort** [comment]
No, but you have a vcpkg.json file somewhere up the tree and are using manifest mode instead of classic mode

**Comment by SamuelMarks** [comment]
@autoantwort Actually the first action (succeeding) has a `vcpkg.json`: https://github.com/offscale/libacquire/tree/1cc1da3e1b2e123a925d0e4ace787e9fcfc95422

The second action (failing) has that same `vcpkg.json`: https://github.com/offscale/libacquire/tree/8a219767393c2cafac998f9ea1126fb16de650db

So not sure how it decides between 'manifest' and 'classic' modes…

**Comment by JackBoosY** [comment]
@ras0219-msft revert #21550 changes in https://github.com/microsoft/vcpkg/pull/21606 yesterday, but it seems not related to that.

**Comment by JackBoosY** [comment]
Using the current vcpkg binary in manifest commandline mode couldn't repro this issue.

**Comment by JackBoosY** [comment]
```
      - name: Install dependencies with vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd "..\vcpkg"
          IF NOT EXIST "buildtrees\libarchive" (
              .\vcpkg install libarchive
          )
```
Please note if you put the manifest file vcpkg.json to vcpkg root, vcpkg will enable manifest mode automaticly.
In manifest mode, you should not pass any port names in install command('.\vcpkg install').

**Comment by SamuelMarks** [comment]
@JackBoosY Yes and on my latest version I do that:
https://github.com/offscale/libacquire/blob/bab3f2580d4c51cf6c633aa3f190889e15ca6e3b/.github/workflows/github-actions.yml#L80
```shell
.\vcpkg install --triplet "%RUNNER_ARCH%-%RUNNER_OS%"
```

But that still doesn't explain why one of those two actions failed and one succeeded. Both had a `vcpkg.json` in repo root. I moved vcpkg down a directory from `%GITHUB_WORKSPACE%\...\vcpkg` to `%GITHUB_WORKSPACE%\vcpkg` (to get the caching action to work). Could that be the issue?

**Comment by autoantwort** [comment]
> I moved vcpkg down a directory from %GITHUB_WORKSPACE%\...\vcpkg to %GITHUB_WORKSPACE%\vcpkg (to get the caching action to work). Could that be the issue?

So you moved vcpkg from next to your workspace into your workspace and in your workspace is a vcpkg.json file.

**Comment by SamuelMarks** [comment]
Okay so it looks in one directory above to see if it's manifest mode or not?

**Comment by JackBoosY** [comment]
> Okay so it looks in one directory above to see if it's manifest mode or not?

If your custom manifest file exists in vcpkg root dir, yes.

**Comment by SamuelMarks** [comment]
(it exists in the directory above vcpkg)

**Comment by JackBoosY** [comment]
> 

If it exists in the parent path of vcpkg, it shouldn't.

**Comment by SamuelMarks** [comment]
Okay well that's the confusing hiccup, see those commits and github action log output (all code is open-source)

**Comment by JackBoosY** [comment]
@BillyONeal Have we changed the rules for the manifest mode?

**Comment by BillyONeal** [comment]
Not as far as I am aware. I confess to still not really understanding what the bug report is. @SamuelMarks The answer to 'has vcpkg changed in the last 24 hours' is usually 'yes'. Can you provide repro steps?

```
PS C:\Dev> git clone git@github.com:offscale/libacquire
Cloning into 'libacquire'...
remote: Enumerating objects: 1344, done.
remote: Counting objects: 100% (1344/1344), done.
remote: Compressing objects: 100% (894/894), done.
remote: Total 1344 (delta 897), reused 801 (delta 355), pack-reused 0
Receiving objects: 100% (1344/1344), 436.90 KiB | 1.75 MiB/s, done.
Resolving deltas: 100% (897/897), done.
PS C:\Dev> cd libacquire
PS C:\Dev\libacquire> git -C ..\vcpkg rev-parse HEAD
3a68454afa67bde8b6e9e741536daa95d3785966
PS C:\Dev\libacquire> ..\vcpkg\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-11-24/vcpkg.exe -> C:\Dev\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\Dev\libacquire> ..\vcpkg\vcpkg.exe install
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
The following packages will be built and installed:
  * bzip2[core]:x86-windows -> 1.0.8#2
    libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x86-windows -> 3.5.2#2
  * libiconv[core]:x86-windows -> 1.16#11
  * liblzma[core]:x86-windows -> 5.2.5#4
  * libxml2[core]:x86-windows -> 2.9.12#4
  * lz4[core]:x86-windows -> 1.9.3#3
  * openssl[core]:x86-windows -> 1.1.1l#4
  * vcpkg-cmake[core]:x64-windows -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-windows -> 2021-11-01
  * zlib[core]:x86-windows -> 1.2.11#13
  * zstd[core]:x86-windows -> 1.5.0#1
Additional packages (*) will be modified to complete this operation.
Restored 0 packages from C:\Users\billy\AppData\Local\vcpkg\archives in 2.314 ms. Use --debug to see more details.
Starting package 1/11: vcpkg-cmake-config:x64-windows
Building package vcpkg-cmake-config[core]:x64-windows...
```

(build output follows) :)

**Comment by LilyWangLL** [comment]
PS E:\Code> .\External\CppLib\vcpkg\vcpkg.exe install zlib
Error: 'install' requires 0 arguments, but 1 were provided.
Example:
  vcpkg install --triplet x64-windows

**Comment by JackBoosY** [comment]
I guess this is by design and we won't rollback this changes.
And I think we should add this to our document to warning the users.

**Comment by BillyONeal** [comment]
> I guess this is by design and we won't rollback this changes. And I think we should add this to our document to warning the users.

Even if this behavior change is intended, the diagnostic is terrible.

**Comment by SamuelMarks** [comment]
> If I'm not wrong, `vcpkg.json` exists in the path where you called vcpkg.exe, right?

Nope, I `cd`'d to the directory first. To be super explicit here are the two yaml files:

_works_
https://github.com/offscale/libacquire/blob/1cc1da3e1b2e123a925d0e4ace787e9fcfc95422/.github/workflows/github-actions.yml#L47
```yml
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: ilammy/msvc-dev-cmd@v1
      - name: Cache vcpkg
        uses: actions/cache@v2
        env:
          cache-name: cache-vcpkg
        with:
          path: ${{ github.workspace }}/../vcpkg
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: clone and bootstrap vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd ..
          IF NOT EXIST "vcpkg" (
              git clone --depth=360 https://github.com/microsoft/vcpkg
              cd vcpkg
              git reset --hard 4a78558
              .\bootstrap-vcpkg.bat
          )
        shell: cmd
      - name: Install dependencies with vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd "..\vcpkg"
          IF NOT EXIST "buildtrees\libarchive" (
              .\vcpkg install libarchive
          )
        shell: cmd
      - name: build
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd ..
          set vcpkg="%cd%\vcpkg"
          dir "%vcpkg%"
          cd "libacquire"
          md "cmake-build-debug"
          cd "cmake-build-debug"
          cmake -DCMAKE_TOOLCHAIN_FILE="%vcpkg%\scripts\buildsystems\vcpkg.cmake" ..
          cmake --build .
        shell: cmd
      - name: test
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd "..\libacquire\cmake-build-debug"
          ctest -C "Debug" .
        shell: cmd
```

_fails_
https://github.com/offscale/libacquire/blob/8a219767393c2cafac998f9ea1126fb16de650db/.github/workflows/github-actions.yml#L47
```yml
  bu
ild_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: ilammy/msvc-dev-cmd@v1
      - name: Cache vcpkg
        uses: actions/cache@v2
        env:
          cache-name: cache-vcpkg
        with:
          path: ${{ github.workspace }}/vcpkg
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: clone and bootstrap vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%"
          IF NOT EXIST "vcpkg" (
              git clone --depth=360 https://github.com/microsoft/vcpkg
              cd "vcpkg"
              git reset --hard d8b9ae5
              .\bootstrap-vcpkg.bat
          )
        shell: cmd
      - name: Install dependencies with vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%\vcpkg"
          IF NOT EXIST "buildtrees\libarchive" (
              .\vcpkg "--version"
              .\vcpkg "install" "libarchive"
          )
        shell: cmd
      - name: build
        run: |
          cd "%GITHUB_WORKSPACE%"
          set vcpkg="%cd%\vcpkg"
          md "cmake-build-debug"
          cd "cmake-build-debug"
          cmake -DCMAKE_TOOLCHAIN_FILE="%vcpkg%\scripts\buildsystems\vcpkg.cmake" ..
          cmake --build .
        shell: cmd
      - name: test
        run: |
          cd "%GITHUB_WORKSPACE%\libacquire\cmake-build-debug"
          ctest -C "Debug" .
        shell: cmd
```

**Comment by SamuelMarks** [comment]
> If I'm not wrong, `vcpkg.json` exists in the path where you called vcpkg.exe, right?

Nope, I `cd`'d to the directory first. To be super explicit here are the two yaml files:

_works_
https://github.com/offscale/libacquire/blob/1cc1da3e1b2e123a925d0e4ace787e9fcfc95422/.github/workflows/github-actions.yml#L47
```yml
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: ilammy/msvc-dev-cmd@v1
      - name: Cache vcpkg
        uses: actions/cache@v2
        env:
          cache-name: cache-vcpkg
        with:
          path: ${{ github.workspace }}/../vcpkg
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: clone and bootstrap vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd ..
          IF NOT EXIST "vcpkg" (
              git clone --depth=360 https://github.com/microsoft/vcpkg
              cd vcpkg
              git reset --hard 4a78558
              .\bootstrap-vcpkg.bat
          )
        shell: cmd
      - name: Install dependencies with vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd "..\vcpkg"
          IF NOT EXIST "buildtrees\libarchive" (
              .\vcpkg install libarchive
          )
        shell: cmd
      - name: build
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd ..
          set vcpkg="%cd%\vcpkg"
          dir "%vcpkg%"
          cd "libacquire"
          md "cmake-build-debug"
          cd "cmake-build-debug"
          cmake -DCMAKE_TOOLCHAIN_FILE="%vcpkg%\scripts\buildsystems\vcpkg.cmake" ..
          cmake --build .
        shell: cmd
      - name: test
        run: |
          cd "%GITHUB_WORKSPACE%"
          cd "..\libacquire\cmake-build-debug"
          ctest -C "Debug" .
        shell: cmd
```

_fails_
https://github.com/offscale/libacquire/blob/8a219767393c2cafac998f9ea1126fb16de650db/.github/workflows/github-actions.yml#L47
```yml
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: ilammy/msvc-dev-cmd@v1
      - name: Cache vcpkg
        uses: actions/cache@v2
        env:
          cache-name: cache-vcpkg
        with:
          path: ${{ github.workspace }}/vcpkg
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: clone and bootstrap vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%"
          IF NOT EXIST "vcpkg" (
              git clone --depth=360 https://github.com/microsoft/vcpkg
              cd "vcpkg"
              git reset --hard d8b9ae5
              .\bootstrap-vcpkg.bat
          )
        shell: cmd
      - name: Install dependencies with vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%\vcpkg"
          IF NOT EXIST "buildtrees\libarchive" (
              .\vcpkg "--version"
              .\vcpkg "install" "libarchive"
          )
        shell: cmd
      - name: build
        run: |
          cd "%GITHUB_WORKSPACE%"
          set vcpkg="%cd%\vcpkg"
          md "cmake-build-debug"
          cd "cmake-build-debug"
          cmake -DCMAKE_TOOLCHAIN_FILE="%vcpkg%\scripts\buildsystems\vcpkg.cmake" ..
          cmake --build .
        shell: cmd
      - name: test
        run: |
          cd "%GITHUB_WORKSPACE%\libacquire\cmake-build-debug"
          ctest -C "Debug" .
        shell: cmd
```
