### ISSUE TITLE
vcpkg in manifest mode installs already-installed packages

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#22819]
On Windows I run vcpkg and it loads from cache but still goes through the slow manifest-mode install later:
https://github.com/offscale/libacquire/blob/169b575/.github/workflows/github-actions.yml#L52

https://github.com/offscale/libacquire/actions

Same experienced (sometimes) after I clear my build dir and run it on macOS. Do we need a new `-DVCPKG_SKIP_INSTALL_IF_INSTALLED` or is this a bug?

**Comment by dg0yt** [comment]
`vcpkg install` invoked from cmake will use the binary directory.
A manual `vcpkg install` in the source directory doesn't know CMake's binary directory. 
So you explicitly ask for two different install locations..

**Comment by mathisloge** [comment]
There is also a good example for a working _single repository_ github actions setup: https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md

**Comment by SamuelMarks** [comment]
@dg0yt 
> A manual `vcpkg install` in the source directory doesn't know CMake's binary directory.

Couldn't it infer from `-DCMAKE_TOOLCHAIN_FILE`, i.e., look relative to that file?

@mathisloge That basically tells me to do nothing in manifest mode. Also the example has no caching.

**Comment by mathisloge** [comment]
> Also the example has no caching.

It works with the binary caching of vcpkg. This is also better, since the github cache action (IIRC) has only 5GB capacity. 

> That basically tells me to do nothing in manifest mode

As the example in https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#github-packages  states "`# Omit this step if you're using manifests`". So your statement is not correct.

**Comment by mathisloge** [comment]
@SamuelMarks just one more personal suggestion:
```yaml
      - name: checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vcpkg"
          ref: <commit_sha>
          path: vcpkg

      - name: "Setup vcpkg"
        run: ./vcpkg/bootstrap-vcpkg.bat
```
so you don't have to do a manual clone via git. 
I'm doing this in my github actions and just takes a few seconds
![image](https://user-images.githubusercontent.com/13556116/151416657-d0f1e0fc-4ad1-4c27-99df-da2c3cb9fe6f.png)

**Comment by dg0yt** [comment]
> > A manual `vcpkg install` in the source directory doesn't know CMake's binary directory.
> 
> Couldn't it infer from `-DCMAKE_TOOLCHAIN_FILE`, i.e., look relative to that file?

That file is only known in the binary dir, not in the source directory. That's the whole story. You can have multiple binary dirs for the same source dir. My main project usually has one for Android, one for MinGW, one for Ubuntu system packages and a few more for alternative configurations.

But you know what the binary dir and target triplet. You can tell `vcpkg install` which directory should be used. This is what the vcpkg toolchain file does when it invokes vcpkg.

**Comment by SamuelMarks** [comment]
@dg0yt Hmm so I did the whole `-DVCPKG_MANIFEST_MODE="OFF"` thing after adding your `actions/checkout@v2` suggestion… but it's not restoring from cache (so is only twice as fast). `IF NOT EXIST "buildtrees\libarchive"` is my condition, should I be doing some fancier GitHub Workflows style solution on cache-hit?

**Comment by dg0yt** [comment]
Where do you set `VCPKG_MANIFEST_MODE=OFF`?

I think it doesn't prevent a second install because it will not use the project source directory (as your plain `vcpkg install` in the source directory does) but the vcpkg root directory (as classic mode does). 
AFAICT the three different ways of invoking `vcpkg install` give three different install tree locations:
- classic (toolchain, manifest mode off): vcpkg root directory
- manifest mode, plain `vcpkg install` in project source directory: project source directory
- manifest mode, implicit `vcpkg install` from toolchain file: project binary directory

AFAIU you wanted to modify the third option to reuse the install tree from the second option, but you got the first option instead (assuming `-DVCPKG_MANIFEST_MODE=OFF`).

I would avoid the second option and stay with the third. I can't say much about GH actions and GH caching because I don't use it. But it shouldn't take magic to cache the vcpkg assets and artifacts even with the third option.

**Comment by mathisloge** [comment]
@SamuelMarks I'm really recommending using binary caching. It's simple to setup when using only one repo. 

Just 
```yml
  - name: 'Setup NuGet Credentials'
    shell: 'bash'
    # Replace <OWNER> with your organization name
    run: >
      ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
      sources add
      -source "https://nuget.pkg.github.com/<OWNER>/index.json"
      -storepasswordincleartext
      -name "GitHub"
      -username "<OWNER>"
      -password "${{ secrets.GITHUB_TOKEN }}"
 ```
after `vcpkg/bootstrap-vcpkg.bat` 

as in https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#github-packages

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by SamuelMarks** [comment]
Yeah ended up getting the regular caching to work, like so:
```yml
steps:
  - uses: actions/checkout@v2

  - name: mkdir
    run: mkdir build

  - name: Cache vcpkg
    id: cache-vcpkg
    uses: actions/cache@v2
    with:
      path: vcpkg
      key: ${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}-project0-0

  - name: checkout vcpkg
    uses: actions/checkout@v2
    with:
      repository: "offscale/vcpkg"
      ref: project0
      path: vcpkg
    if: steps.cache-vcpkg.outputs.cache-hit != 'true'

  - name: Setup vcpkg (Windows)
    run: ./vcpkg/bootstrap-vcpkg.bat
    if: matrix.os == 'windows-latest'

  - name: "Setup vcpkg (non Windows)"
    run: ./vcpkg/bootstrap-vcpkg.sh
    if: matrix.os != 'windows-latest'

  - name: configure (with vcpkg on Windows)
    working-directory: ./build
    run: |
      cmake -DCMAKE_TOOLCHAIN_FILE="vcpkg\scripts\buildsystems\vcpkg.cmake" ..
    shell: cmd
    if: matrix.os == 'windows-latest'

  - name: configure (with vcpkg on non-Windows)
    working-directory: ./build
    run: |
      cmake -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" ..
    if: matrix.os != 'windows-latest'

  - name: build
    working-directory: ./build
    run: cmake --build .

  - name: test
    working-directory: ./build
    run: ctest -C Debug .
```
