### ISSUE TITLE
[vcpkg icu] build failure - ubuntu & macos

### ISSUE THREAD

**Issue by dehilsterlexis** [microsoft/vcpkg#26990]
**Host Environment**

Ubuntu-latest

Here is my yml script which has been working fine until now for vcpkg:

```
name: Test Linux

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
      
jobs:
  job:
    name: Linux Compile Test
    runs-on: ubuntu-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Vcpkg Bootstrap Shell
        run: ./bootstrap-vcpkg.sh
        shell: bash
        working-directory: vcpkg

      - name: Install ICU
        run: vcpkg install
        working-directory: vcpkg

      - name: Make build directory
        run: mkdir build

      - name: Generate Solution Linux
        run: cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_BUILD_TYPE=release -B build -S .

      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Cmake Build all targets Linux
        run: cmake --build build/ --target all

      - name: Test executable --version
        run: ./bin/nlp.exe --version || true

      - uses: actions/upload-artifact@v3
        with:
          name: nlp.exe
          path: bin

      - uses: actions/upload-artifact@v3
        with:
          name: ibicutu.a
          path: vcpkg_installed/x64-linux/lib/libicutu.a

      - uses: actions/upload-artifact@v3
        with:
          name: libicuuc.a
          path: vcpkg_installed/x64-linux/lib/libicuuc.a
```

**To Reproduce**

(see yml script above)
`./vcpkg install`

**Failure logs**

Here is a link to the failure: https://github.com/VisualText/nlp-engine/actions/runs/3127306656/jobs/5073787389

```
Run vcpkg install
  vcpkg install
  shell: /usr/bin/bash -e {0}
  env:
    VCPKG_DEFAULT_TRIPLET: x64-linux
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
    icu[core]:x64-linux -> 71.1
Restored 0 package(s) from /home/runner/.cache/vcpkg/archives in 14.6 us. Use --debug to see more details.
Installing 1/1 icu:x64-linux...
Building icu[core]:x64-linux...
-- Downloading https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-src.tgz -> icu4c-71_1-src.tgz...
-- Extracting source /usr/local/share/vcpkg/downloads/icu4c-71_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Applying patch check-autoconf-archive.patch
-- Using source at /usr/local/share/vcpkg/buildtrees/icu/src/c-71_1-src-08c83f7de1.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
-- Finished generating configure for x64-linux
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/c-71_1-src-08c83f7de1.clean/source/configure  \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/home/runner/work/nlp-engine/nlp-engine/vcpkg_installed/x64-linux/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: /usr/local/share/vcpkg/buildtrees/icu/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /usr/local/share/vcpkg/buildtrees/icu/config-x64-linux-dbg-config.log
      /usr/local/share/vcpkg/buildtrees/icu/config-x64-linux-dbg-out.log
      /usr/local/share/vcpkg/buildtrees/icu/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:797 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:53 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)


error: building icu:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[icu]+Build+error
Include '[icu] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: [2](https://github.com/VisualText/nlp-engine/actions/runs/3127306656/jobs/5073787389#step:4:2)022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: d526[3](https://github.com/VisualText/nlp-engine/actions/runs/3127306656/jobs/5073787389#step:4:3)2d9a 2022-09-21 ([5](https://github.com/VisualText/nlp-engine/actions/runs/3127306656/jobs/5073787389#step:4:5) days ago)


Please use the prefilled template from /home/runner/work/nlp-engine/nlp-engine/vcpkg_installed/vcpkg/issue_body.md when reporting your issue.
Error: Process completed with exit code 1.
```

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
