### ISSUE TITLE
Official Azure Pipelines task?

### ISSUE THREAD

**Issue by AnthonyMastrean** [microsoft/vcpkg#27011]
It would be awesome to see an official Azure Pipelines task in the [marketplace](https://marketplace.visualstudio.com/search?target=AzureDevOps&category=Azure%20Pipelines&sortBy=Installs)!

The [2019 update post](https://devblogs.microsoft.com/cppblog/vcpkg-2019-07-update/) recommended the third-party [CppBuildTasks task](https://marketplace.visualstudio.com/items?itemName=lucappa.cmake-ninja-vcpkg-tasks). That project hasn't aged well and doesn't support [manifest mode](https://github.com/lukka/CppBuildTasks/issues/67) nor [binary caching](https://devblogs.microsoft.com/cppblog/vcpkg-accelerate-your-team-development-environment-with-binary-caching-and-manifests/).

Following are the custom tasks I use to use vcpkg in manifest mode (assumes a `vcpkg.json` in the workspace root and an accessible NuGet feed):

**azure-pipelines.yml**

```yml
pool:
  vmImage: windows-latest

variables:
  VCPKG_ARTIFACT_URL: 'https://.../nuget/v3/index.json'
  VCPKG_BINARY_SOURCES: clear;nuget,$(VCPKG_ARTIFACT_URL),readwrite
  VCPKG_GIT_URL: 'https://github.com/microsoft/vcpkg.git'
  VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
  VCPKG_USE_NUGET_CACHE: true

steps:
- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet'
- task: CmdLine@2
  displayName: 'Setup vcpkg'
  inputs:
    script: |
      git clone --quiet $(VCPKG_GIT_URL) $(VCPKG_ROOT)
      call $(VCPKG_ROOT)\bootstrap-vcpkg.bat -disableMetrics
      $(VCPKG_ROOT)\vcpkg.exe integrate install
      $(VCPKG_ROOT)\vcpkg.exe install
```
