### ISSUE TITLE
[icu] Build error in github action yml file windows

### ISSUE THREAD

**Issue by dehilsterlexis** [microsoft/vcpkg#30664]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

It's failing in a place where it was running fine before. I have changed nothing and it compiles on my windows machine fine. Here is part of the github yml script [build-windows.yml](https://github.com/VisualText/nlp-engine/blob/master/.github/workflows/build-windows.yml):

```
name: Windows

on:
  pull_request:
    types: [opened, synchronize, reopened]
 
jobs:
  build_engine:
    name: Build NLP-ENGINE
    runs-on: windows-2019

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Vcpkg bootstrap Windows
        run: bootstrap-vcpkg.bat
        working-directory: vcpkg

      - name: Install 3rd Party
        run: vcpkg install
        working-directory: vcpkg
```

```
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(960): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 13us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2790us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 18.1156325 s (18106220us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:26 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:67 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:345 (z_vcpkg_acquire_msys_declare_package)
  scripts/cmake/vcpkg_configure_make.cmake:207 (vcpkg_acquire_msys)
  ports/icu/portfile.cmake:50 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)


error: building icu:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[icu]+Build+error
Include '[icu] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: e51afe46 2023-01-17 (3 months ago
```
