### ISSUE TITLE
[cppunit] build failure

### ISSUE THREAD

**Issue by masx200** [microsoft/vcpkg#30815]
### Operating system

github action macos-latest

### Compiler

xcode clang

### Steps to reproduce the behavior

```Shell
/usr/local/share/vcpkg/vcpkg install cppunit:x64-osx
```

### Failure logs
```
/usr/local/share/vcpkg/vcpkg install cppunit:x64-osx
Computing installation plan...
The following packages will be built and installed:
    cppunit[core]:x64-osx -> 1.15.1#3
Detecting compiler hash for triplet x64-osx...
Restored 0 package(s) from /Users/runner/.cache/vcpkg/archives in 60.9 us. Use --debug to see more details.
Installing 1/1 cppunit:x64-osx...
Building cppunit[core]:x64-osx...
-- Downloading https://dev-www.libreoffice.org/src/cppunit-1.15.1.tar.gz -> cppunit-1.15.1.tar.gz...
-- Extracting source /usr/local/share/vcpkg/downloads/cppunit-1.15.1.tar.gz
-- Using source at /usr/local/share/vcpkg/buildtrees/cppunit/src/cppunit-1-60beb2c90e.clean
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Generating configure for x64-osx
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/local/bin/autoreconf -vfi
    Working Directory: /usr/local/share/vcpkg/buildtrees/cppunit/src/cppunit-1-60beb2c90e.clean/
    Error code: 2
    See logs for more information:
      /usr/local/share/vcpkg/buildtrees/cppunit/autoconf-x64-osx-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:626 (vcpkg_execute_required_process)
  ports/cppunit/portfile.cmake:34 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)


error: building cppunit:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+cppunit
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[cppunit]+Build+error&body=Copy+issue+body+from+%2Fusr%2Flocal%2Fshare%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
You can also sumbit an issue by running (GitHub cli must be installed):
    gh issue create -R microsoft/vcpkg --title "[cppunit] Build failue" --body-file /usr/local/share/vcpkg/installed/vcpkg/issue_body.md
error: execv(/usr/local/share/vcpkg/vcpkg install cppunit:x64-osx) failed(1)
  => install vcpkg::cppunit latest .. failed
error: install failed!
Error: Process completed with exit code 255.
```
### Additional context

https://github.com/masx200/leetcode-treenode-cpp/actions/runs/4684134914/workflow

```yaml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  # Path to the solution file relative to the root of the project.


  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    

    - name: install

      run: |
            brew install xmake
                  cd ~
                  git clone https://gitcode.net/mirrors/microsoft/vcpkg
                  cd vcpkg
                  sh bootstrap-vcpkg.sh
                  ~/vcpkg/vcpkg integrate install
                  ~/vcpkg/vcpkg integrate bash
                  
                   cd ~
                   bash <(curl -fsSL https://xmake.io/shget.text)       
    - name: make

      run: xmake build -vy

    - name: test

      run: xmake run -v

```
