### ISSUE TITLE
[RE2] build failure

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#38146]
### Operating system

Ubuntu 22.04

### Compiler

GCC 13

### Steps to reproduce the behavior

```Shell
`vcpkg install re2`
```

### Failure logs

Building re2:x64-linux@2024-04-01#1...
-- Downloading https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1 -> 9ebe4a22cad8a025b68a9594bdff3c047a111333.patch...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] Detected CI environment: GitHub_Actions
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1 --create-dirs --output /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/downloads/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.5452.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   112984 us
[DEBUG] Trying to hash /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/downloads/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.5452.part
[DEBUG] /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/downloads/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.5452.part has hash 83c1a4cc4ddd6e1443f5201f7f00cf6a0729d0a0fb8fc5068c3d80766238d72f019f1fddaeffebcc2d4322a07daf2203214121cdda039b10a5f39214b9fa8647
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1
File: /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/downloads/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.5452.part
Expected hash: 167a0153bf24e77db2b8555a7d6391acf740dc4720a71e6ce19a3533c7e0a49923d9584ff32544a454837a25eedace00cb2ef9ddbf[425](https://github.com/diehard2/vcpkg_ci_debug/actions/runs/8657158723/job/23738865336#step:4:426)0deb5f2c5aeda04ac26
Actual hash: 83c1a4cc4ddd6e1443f5201f7f00cf6a0729d0a0fb8fc5068c3d80766238d72f019f1fddaeffebcc2d4322a07daf2203214121cdda039b10a5f39214b9fa8647

### Additional context

github action that reproduces the error

``` 
name: CI

on:
  workflow_dispatch:


jobs:
  compile:
    name: VCPKG DEBUG
    runs-on: ubuntu-latest
    steps:
    - name: Install package
      run: |
        sudo apt-get update
        sudo apt-get install perl autoconf-archive ninja-build cmake pkg-config
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        vcpkg/bootstrap-vcpkg.sh
        env
    - name: Install grpc
      run: |
          vcpkg/vcpkg install re2
```
