### ISSUE TITLE
[libsystemd] Build error on x64-linux

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#42884]
### Operating system

rockylinux 9.5

### Compiler

gcc

### Steps to reproduce the behavior
running on github actions.yml is:
```
name: rocky build workflows

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: install library
        run: |
            dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm -y
            dnf config-manager --enable crb
            dnf install git gcc g++ gdb make nasm -y

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     

      - name: vcpkg install
        run: |
            cd vcpkg
            dnf install --allowerasing curl zip unzip tar autoconf libtool python3-jinja2 -y
            dnf install perl-IPC-Cmd perl-CPAN bison flex -y
            yes | cpan IPC::Cmd

            ./bootstrap-vcpkg.sh
            # ./vcpkg install libiconv:x64-linux openssl:x64-linux curl[http2]:x64-linux mongo-c-driver[openssl]:x64-linux libmariadb[openssl]:x64-linux libpq[openssl]:x64-linux zlib:x64-linux minizip:x64-linux sqlite3:x64-linux nghttp2:x64-linux
            ./vcpkg install ffmpeg[all-nonfree,iconv,drawtext,fontconfig,amf,aom,ass,fdk-aac,nvcodec,opengl,opencl,qsv,x264,x265,webp]:x64-linux
```

Because vcpkg failed to execute and exited, the error log cannot be obtained. How to obtain the error log in this case?

### Failure logs

Installing 20/66 libsystemd:x64-linux@256.4...
Building libsystemd:x64-linux@256.4...
-- Found Python version '3.9.19 at /usr/bin/python3'
-- Using meson: /__w/test/test/vcpkg/downloads/tools/meson-1.6.0-ac58a9/meson.py
Downloading systemd-systemd-v256.4.tar.gz
Successfully downloaded systemd-systemd-v256.4.tar.gz.
-- Extracting source /__w/test/test/vcpkg/downloads/systemd-systemd-v256.4.tar.gz
-- Applying patch disable-warning-nonnull.patch
-- Applying patch only-libsystemd.patch
-- Applying patch pkgconfig.patch
-- Using source at /__w/test/test/vcpkg/buildtrees/libsystemd/src/v256.4-825386a66f.clean
-- Configuring x64-linux-dbg
-- Getting CMake variables for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/python3 -I /__w/test/test/vcpkg/downloads/tools/meson-1.6.0-ac58a9/meson.py setup -Dmode=release -Dstatic-libsystemd=pic -Dtests=false -Ddns-over-tls=false -Dtranslations=false -Dacl=disabled -Dapparmor=disabled -Daudit=disabled -Dblkid=disabled -Dbpf-framework=disabled -Dbzip2=disabled -Ddbus=disabled -Delfutils=disabled -Dfdisk=disabled -Dgcrypt=disabled -Dglib=disabled -Dgnutls=disabled -Dkmod=disabled -Dlibcurl=disabled -Dlibcryptsetup=disabled -Dlibfido2=disabled -Dlibidn=disabled -Dlibidn2=disabled -Dlibiptc=disabled -Dmicrohttpd=disabled -Dopenssl=disabled -Dp11kit=disabled -Dpam=disabled -Dpcre2=disabled -Dpolkit=disabled -Dpwquality=disabled -Dpasswdqc=disabled -Dseccomp=disabled -Dselinux=disabled -Dtpm2=disabled -Dxenctrl=disabled -Dxkbcommon=disabled -Dzlib=disabled -Dlz4=enabled -Dxz=enabled -Dzstd=enabled --backend ninja --wrap-mode nodownload -Doptimization=plain --native /__w/test/test/vcpkg/buildtrees/libsystemd/meson-x64-linux-dbg.log --libdir lib --pkgconfig.relocatable -Ddebug=true --prefix /__w/test/test/vcpkg/packages/libsystemd_x64-linux/debug --includedir ../include --pkg-config-path ['/__w/test/test/vcpkg/installed/x64-linux/debug/lib/pkgconfig','/__w/test/test/vcpkg/installed/x64-linux/share/pkgconfig'] -Dcmake_prefix_path=['/__w/test/test/vcpkg/installed/x64-linux/debug','/__w/test/test/vcpkg/installed/x64-linux'] /__w/test/test/vcpkg/buildtrees/libsystemd/src/v256.4-825386a66f.clean
    Working Directory: /__w/test/test/vcpkg/buildtrees/libsystemd/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /__w/test/test/vcpkg/buildtrees/libsystemd/config-x64-linux-dbg-meson-log.txt.log
      /__w/test/test/vcpkg/buildtrees/libsystemd/config-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:468 (vcpkg_execute_required_process)
  ports/libsystemd/portfile.cmake:17 (vcpkg_configure_meson)
  scripts/ports.cmake:196 (include)

error: building libsystemd:x64-linux failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle libsystemd:x64-linux: 6.8 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libsystemd
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libsystemd]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2F__w%2Ftest%2Ftest%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

Error: Process completed with exit code 1.
