### ISSUE TITLE
[ffmpeg] build failure on x64-linux and x64-linux-release

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#42919]
### Operating system

rockylinux9

### Steps to reproduce the behavior

```Shell
./vcpkg install ffmpeg[all-nonfree,iconv,drawtext,fontconfig,amf,ass,fdk-aac,nvcodec,qsv,x264,x265]:x64-linux-release
```

### Failure logs

-- Extracting source /__w/test/test/vcpkg/downloads/ffmpeg-ffmpeg-n7.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0002-fix-msvc-link.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-dependencies.patch
-- Applying patch 0005-fix-nasm.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0013-define-WINVER.patch
-- Applying patch 0020-fix-aarch64-libswscale.patch
-- Applying patch 0024-fix-osx-host-c11.patch
-- Applying patch 0040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch
-- Applying patch 0041-add-const-for-opengl-definition.patch
-- Applying patch 0043-fix-miss-head.patch
-- Using source at /__w/test/test/vcpkg/buildtrees/ffmpeg/src/n7.1-d40f62baf3.clean
-- Getting CMake variables for x64-linux-release
-- Building Options: --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --disable-autodetect --target-os=linux --enable-pthreads --cc=cc --host_cc=cc --cxx=c++ --nm=nm --ar='ar' --ranlib=ranlib --strip=strip --enable-nonfree --enable-gpl --enable-version3 --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --enable-alsa --enable-amf --enable-libaom --enable-libass --disable-avisynth --enable-bzlib --enable-libdav1d --enable-libfdk-aac --enable-libfontconfig --enable-libharfbuzz --enable-libfreetype --enable-libfribidi --enable-iconv --enable-libilbc --enable-lzma --enable-libmp3lame --enable-libmodplug --enable-cuda --enable-nvenc --enable-nvdec --enable-cuvid --enable-ffnvcodec --enable-opencl --enable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-openssl --enable-libopus --enable-sdl2 --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --disable-libtensorflow --disable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-zlib --enable-libsrt --enable-libmfx --enable-encoder=h264_qsv --enable-decoder=h264_qsv --enable-cross-compile --pkg-config="/bin/pkg-config" --pkg-config-flags=--static
-- Building Release Options: --enable-optimizations --extra-ldflags=-L"/__w/test/test/vcpkg/installed/x64-linux-release/lib"
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/bash ./build.sh
    Working Directory: /__w/test/test/vcpkg/buildtrees/ffmpeg/x64-linux-release-rel
    Error code: 1
    See logs for more information:
      /__w/test/test/vcpkg/buildtrees/ffmpeg/build-x64-linux-release-rel-config.log
      /__w/test/test/vcpkg/buildtrees/ffmpeg/build-x64-linux-release-rel-out.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:737 (vcpkg_execute_required_process)
  scripts/ports.cmake:196 (include)

error: building ffmpeg:x64-linux-release failed with: BUILD_FAILED[build-x64-linux-release-rel-config.log](https://github.com/user-attachments/files/18244065/build-x64-linux-release-rel-config.log)
[build-x64-linux-release-rel-out.log](https://github.com/user-attachments/files/18244064/build-x64-linux-release-rel-out.log)

### Additional context

build on github actions.
```
name: rocky build workflows

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: install library
        run: |
            dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm -y
            dnf config-manager --enable crb
            dnf install git gcc g++ gdb make nasm -y

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     

      - name: vcpkg install
        run: |
            cd vcpkg
            dnf install --allowerasing curl zip unzip tar autoconf libtool python3-jinja2 diffutils -y
            dnf install perl-IPC-Cmd perl-CPAN bison flex -y
            yes | cpan IPC::Cmd

            ./bootstrap-vcpkg.sh
            #./vcpkg install libiconv:x64-linux-release openssl:x64-linux-release curl[http2]:x64-linux-release mongo-c-driver[openssl]:x64-linux-release libmariadb[openssl]:x64-linux-release libpq[openssl]:x64-linux-release zlib:x64-linux-release minizip:x64-linux-release sqlite3:x64-linux-release nghttp2:x64-linux-release
            ./vcpkg install ffmpeg[all-nonfree,iconv,drawtext,fontconfig,amf,ass,fdk-aac,nvcodec,qsv,x264,x265]:x64-linux-release 2>&1 | tee /tmp/vcpkg_install.log
            cat /tmp/vcpkg_install.log

      - name: Upload vcpkg install log
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg_logs
          path: |
            /__w/test/test/vcpkg/buildtrees/ffmpeg/build-x64-linux-release-rel-config.log
            /__w/test/test/vcpkg/buildtrees/ffmpeg/build-x64-linux-release-rel-out.log
          
```
