### ISSUE TITLE
[mongo-c-driver:arm64-ios] build failure

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#42995]
### Operating system

macos-14

### Steps to reproduce the behavior

```Shell
./vcpkg install 'mongo-c-driver:arm64-ios'
```

### Failure logs

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /opt/homebrew/bin/cmake /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/src/1.29.1-a1002e361c.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Users/runner/work/test/test/vcpkg/packages/mongo-c-driver_arm64-ios/debug -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DENABLE_SNAPPY=OFF -DENABLE_ZSTD=OFF -DENABLE_SSL=DARWIN -DBUILD_VERSION=1.29.1 -DUSE_BUNDLED_UTF8PROC=OFF -DUSE_SYSTEM_LIBBSON=ON -DENABLE_CLIENT_SIDE_ENCRYPTION=OFF -DENABLE_EXAMPLES=OFF -DENABLE_SASL=OFF -DENABLE_SHM_COUNTERS=OFF -DENABLE_STATIC=ON -DENABLE_TESTS=OFF -DENABLE_UNINSTALL=OFF -DENABLE_ZLIB=SYSTEM -DCMAKE_DISABLE_FIND_PACKAGE_Python=ON -DCMAKE_DISABLE_FIND_PACKAGE_Python3=ON -DPKG_CONFIG_EXECUTABLE=/opt/homebrew/bin/pkg-config -DCMAKE_MAKE_PROGRAM=/opt/homebrew/bin/ninja -DCMAKE_SYSTEM_NAME=iOS -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/runner/work/test/test/vcpkg/scripts/toolchains/ios.cmake -DVCPKG_TARGET_TRIPLET=arm64-ios -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/Users/runner/work/test/test/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/Users/runner/work/test/test/vcpkg -D_VCPKG_INSTALLED_DIR=/Users/runner/work/test/test/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/arm64-ios-dbg
    Error code: 1
    See logs for more information:
      /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-CMakeCache.txt.log
      /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-CMakeConfigureLog.yaml.log
      /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-out.log
      /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-err.log

error log:
CMake Error at src/libmongoc/CMakeLists.txt:818 (message):
  ENABLE_SRV is “ON”, but we were unable to find a name resolution
  library

what is the library?

### Additional context

error log files:
/Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-CMakeCache.txt.log
/Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-CMakeConfigureLog.yaml.log
/Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-out.log
/Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-err.log

[vcpkg_logs.zip](https://github.com/user-attachments/files/18271746/vcpkg_logs.zip)

build on github actions.

```
name: ios build workflows

on:
  push:
    branches: 
      - main

permissions:
  contents: read
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-14
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: brew install
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg              
          
      - name: vcpkg install
        run: |
            brew install cmake ninja pkg-config autoconf nasm
            cd vcpkg
            ./bootstrap-vcpkg.sh
            ./vcpkg install 'mongo-c-driver:arm64-ios' 2>&1 | tee /tmp/vcpkg_install.log
            cat /tmp/vcpkg_install.log

      - name: Upload vcpkg install log
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg_logs
          path: |
            /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-CMakeCache.txt.log
            /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-CMakeConfigureLog.yaml.log
            /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-out.log
            /Users/runner/work/test/test/vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-err.log

         
```
